### ISSUE TITLE
Determine broad structure/order of class

### ISSUE THREAD

**Issue by jesse-stew** [crowjm/portfolio-class#1]

**Comment by jesse-stew** [comment]
Most pressing issue-need to be as specific as possible, with realistic goals, and determine ASAP.

**Comment by jesse-stew** [comment]
A way to help with this would be to brainstorm all of the things that would need to be taught in order to have the students reach their end goal of having a live portfolio. From there, items can be sorted by priority and feasibility.

**Comment by jesse-stew** [comment]
Initial thoughts on what my ideal class would contain (in no particular order):
- git/github or surge (Abby's suggestion)
- HTML 
  - h, p, and anchor tags
  - images
  - layout: either floats or flexbox
  - spans
  - divs, sections, articles, asides
  - lists
- CSS using percentages and ems/rems 
  - color
  - background
  - spacing: margins and padding
  - height and width
  - font-family, font-size, font-weight
  - line-height
  - clearfix if floats are use for layout
- RWD
- sketching
- photoshop basics: for style tiles and image optimization
- color theory
- typography
- accessibility basics
- dev tools/debugging

This list is ambitious, even if class time is 2.5-3 hours per week. Maybe some of it would be better suited for reading before class/as a homework assignment and then reviewed briefly during class? Maybe some could be next steps after the class that we could send examples and resources on? Teach ALL THE THINGS. 🎉

**Comment by jesse-stew** [comment]
These are the groups from the above that form for me. I feel like this could be done over the course of 4 weeks if class time is in the 2.5-3 hour range and if portfolios are only 2-3 pages: about, work, contact (or something like that).
1. getting started with design: color theory, typography, sketching (intro RWD here maybe?), PS basics, accessibility basics for design (color contrast, etc).
   - homework: create a couple of style tiles, find images to use for portfolio and optimize
2. getting started with code: HTML, accessiblity basics for code (how to write a good alt attribute for images, etc.) and getting project set up with either git/github (git init, add, commit, push) or surge
   - homework: create structure for portfolio pages
3. add style: css, dev/debugging tools, more in-depth RWD: media queries
   - homework: add responsive styles to all pages
4. ship it!: save for questions and help with making site live on the interwebz

**Comment by dawndelatte** [comment]
Thanks for putting this together Jesse! I just have a couple of ideas/comments on this. But overall I think it's a great plan. 

Design –
1) Accessibility can be tied in with color theory and typography, etc., instead of being a separate idea. Ps basics (explaining image optimization and some basics to get them comfortable with making a style tile. _using Samantha Warren's as a resource perhaps?_) 
Here's my idea for structure: 
- Accessibility, color theory, type, design
- Ideation (inspiration, word lists, content strategy) - this will help with throughout the whole series I think
- Overview of Ps for image optimization and style tiles
- Sketching (RWD / site layout) 
- Homework: Continue with style tiles, images, and begin to gather other content (bio, projects write ups, etc.)

Code –
2) I think keeping HTML & CSS on separate days is a good idea. Like we discussed earlier, if using Surge will be similar to git/github then I think github is the better option (but we need to do a little more research.) Also, as we discussed, "timeboxing" and allowing them to listen, then workshop, then pair program or work it out on their own I think will be helpful so that they get some confidence in problem solving before taking it home to work on until the next week. 

3) For this class, were you thinking that you would go through CSS for the their page and then have them add the media queries as homework? I think this could work, as long as we give them some solid examples of styles they can carry through the other pages/screen sizes. We may need to spend more time here on layout stuff (flexbox or floating) because that's going to be harder to problem solve on their own. You mentioned this in your HTML section at the very top, were you going to cover the structural CSS first? The only problem I can see with this is showing structural stuff without padding and width and height might be confusing. 

4) So, I'm wondering about the Q&A structure here. Do you think it would be more helpful to have a time in the beginning of each class to answer homework questions? Or save it all for this class? I don't want them getting hung up and then having to rehash a lot of stuff on the last night. It would be nice if this was saved for smaller bugs and questions on how they can expand on the site perhaps?

I think there is a big opportunity for reading resources in the design section so that we can focus more on the style tiles and sketches. For code, I think showing them codepen or other more tutorial based stuff to do outside of the class would be good (like the flexbox froggy game or MDN / resources for syntax, etc.)

Hope this helps! Let me know if I can help clarify or answer any questions about this feedback. :)

**Comment by jesse-stew** [comment]
1. Absolutely think that accessibility can be tied in with color and typography instead of being a separate idea. My reasoning for listing it explicitly was to make sure we cover it. Definitely agree with using a style tile of Samantha Warren’s (credit where credit is due, y’know). We can also show ours that we create for the example projects as well. Good call adding ideation to this and gathering other content for part of the homework.
2. I looked into Surge. It’s only got a CLI and is an npm package, so we would need to get everyone to have the most recent version of Node installed. It’s just one command to set up and upload the project (from my understanding). So less work than GitHub, yes, but in the back of my mind I just get this knot in my stomach thinking about if someone loses their work somehow. 
   Timeboxing is key for whatever activity we do, but we can dive deeper into thinking about those once we have weekly structure determined.
3. For the CSS class, I was thinking we go through one of their page layouts responsively, and then students have the other pages to do for homework. That way we can talk about media queries, layout, etc. I’m confused as to what you mean when you’re asking about covering structural CSS first-could you clarify?
4. Definitely think that the start of each class can and should have time for questions about the homework. With this class, I was thinking broader questions/clarification, and then saving for questions about the process of making it live (moreso if we use GitHub). I think the goal of the last class should be tying it all together and giving them ideas of what else they can do. 

I’ve got resources for each class as an item in #8. I think they should be sent out a week before each class so that students have time to review them, get a little familiar with the content, and have questions at the ready for class.

**Comment by jesse-stew** [comment]
@dawndelatte see above ^

**Comment by jesse-stew** [comment]
Structure ideas, updated:
1. Week One - Intro to Design
   - Color theory and typography, including accessibility
   - Ideation (inspiration, word lists, content strategy)
   - Overview of Ps for image optimization and style tiles
   - Sketching responsively
   - Homework: Continue with style tiles (2-3), optimize images, and gather other content
2. Week Two - Intro to HTML & Project Set Up
   - h, p, and anchor tags
   - images, including how to write a meaningful alt attribute
   - layout: either floats or flexbox
   - spans
   - divs, sections, articles, asides
   - lists
   - git/github or surge
   - Homework: complete HTML for all 3 pages
3. Week Three - Intro to CSS & RWD
   - color
   - background
   - spacing: margins and padding
   - height and width
   - font-family, font-size, font-weight
   - line-height
   - clearfix if floats are use for layout
   - RWD: media queries & using percentages
   - Chrome dev tools and debugging
   - note: CSS using ems/rems
   - Homework: complete responsive styles for all 3 pages
4. Week Four - Ship It
   - questions/ideas: what to do next, remaining questions
   - if GitHub, checking out to `gh-pages` branch and pushing, where to find site. 
   - it Surge, have class open for questions about other things they want to learn, maybe make some demos about animations, transitions, pseudo classes, etc.

**Comment by dawndelatte** [comment]
@crowjm for clarification, I was asking if we would be covering CSS in with week two's HTML class. (Which it looks like that's a yes). So I'm curious about how we introduce floats or flexbox without some of the other "structural" (maybe layout is a better word) CSS stuff like width, height, and margins/padding on divs. 

**update** You can disregard this really, since we chatted about it in slack ;)

**Comment by jesse-stew** [comment]
Typo on my end; we'll be keeping content and styles separate. 

Also, from earlier discussion: we'll use Git & GitHub and floats/clearfix for layout.

**Comment by jesse-stew** [comment]
**most up to date class structure**
1. Week One - Intro to Design
   - Color theory and typography, including accessibility
   - Ideation (inspiration, word lists, content strategy)
   - Overview of Ps for image optimization and style tiles
   - Sketching responsively
   - Homework: Continue with style tiles (2-3), optimize images, and gather other content
2. Week Two - Intro to HTML & Project Set Up
   - h, p, and anchor tags
   - images, including how to write a meaningful alt attribute
   - spans
   - divs, sections, articles, asides
   - lists
   - git/github
   - Homework: complete HTML for all 3 pages
3. Week Three - Intro to CSS & RWD
   - color
   - background
   - spacing: margins and padding
   - height
   - layout: floats and clearfix
   - font-family, font-size, font-weight
   - line-height
   - RWD: media queries & using percentages
   - Chrome dev tools and debugging
   - note: CSS using ems/rems
   - Homework: complete responsive styles for all 3 pages
4. Week Four - Ship It 🚀 
   - questions/ideas: what to do next, remaining questions
   - checking out to gh-pages branch and pushing, where to find site.
   - Have on the ready: demos about animations, transitions, pseudo classes, etc.

**Comment by jesse-stew** [comment]
Closing for now; we can re-open if we need to change structure
