### ISSUE TITLE
Week Four

### ISSUE THREAD

**Issue by jesse-stew** [crowjm/portfolio-class#6]
- [x] teaching activities
- [x] demos/examples
- [x] slides
- [x] homework

**Comment by jesse-stew** [comment]
Week Four - Ship It 🚀
- questions/ideas: what to do next, remaining questions
- installing node & surge.sh
- Have on the ready: demos about animations, transitions, pseudo classes, etc.

**Comment by jesse-stew** [comment]
@dawndelatte what are your thoughts on week 4 being split between questions from week 3, ways to jeuje up site (hovers, animations, transitions, etc), and shipping it?

**Comment by jesse-stew** [comment]
Also got a request for SVG animations last night. Adding that to the list.

**Comment by jesse-stew** [comment]
reset.css

**Comment by dawndelatte** [comment]
@crowjm I think the outline and slides for week four look great! Are we going to make time for questions at the beginning? I don't want to spend too much time doing that, but since no one showed last week, I imagine there will be some. Here are a couple of things I thought of that could be helpful as extra resources:

http://samkapila.com/command-line-starter-kit/
http://samkapila.com/design-starter-kit/
http://michellechild.com/website_checklist/ < This one is a little wonky though, may be worth recreating something like this real quick?
http://tutsplus.com/ <For design and dev tutorials
https://teamtreehouse.com/home < for code courses/tutorials
http://codepen.io/ <encourage them to set up an account and follow us and start playing around in here

**Comment by jesse-stew** [comment]
@dawndelatte yep, time for CSS questions in the beginning. 

👍 🚀 🎉 for the resources, added to week4.md
